### ISSUE TITLE
bump to 0.3.13

### ISSUE THREAD

**Issue by nickmiller-wf** [chenglou/react-treeview#23]
I found the addition of the `tree-view_item` class to be extremely useful. Would you be willing to bump a version?

Thanks for your work on this component!

**Comment by chenglou** [comment]
How about a brand new repo? =)

https://github.com/chenglou/react-treeview/blob/d3758b277b23111db742d1033151f6dca6c9e93e/HISTORY.md#040-july-31th-2015

**Comment by nickmiller-wf** [comment]
:+1: Thanks!
