### ISSUE TITLE
checkbox alongwith treeview

### ISSUE THREAD

**Issue by nsisodiya** [chenglou/react-treeview#31]
something like this ?
how to do it ?

![tree with checkbox nodes](https://cloud.githubusercontent.com/assets/333455/14101229/aa862a12-f5b0-11e5-96f3-339a42f71f06.gif)

**Comment by chenglou** [comment]
Thought about that. Instead of letting the tree view handle it, you could wrap the component you're passing to the tree view with another component. This way the tree view stays agnostic to this feature. 

Does that make sense? Closing this but feel free to ask more =].
