### ISSUE TITLE
Be case sensitive for imports in demo/index.js

### ISSUE THREAD

**Issue by fleximus** [chenglou/react-treeview#32]
Hi,

I had errors while trying to run the demos. For me, it helped to patch the `demos/index.js` file. I'm on FreeBSD/Linux, so case sensitivity is important but I wonder no one else had this issue before.

Here's the quick patch: 
<pre><code>
--- demos/index.js.orig 2016-04-15 22:52:17.165870132 +0200
+++ demos/index.js      2016-04-15 22:53:22.981871256 +0200
@@ -1,7 +1,7 @@
 import React from 'react';
 import ReactDOM from 'react-dom';
-import Controlled from './Controlled';
-import Uncontrolled from './Uncontrolled';
+import Controlled from './controlled';
+import Uncontrolled from './uncontrolled';

 ReactDOM.render(<Controlled />, document.getElementById('controlled'));
 ReactDOM.render(<Uncontrolled />, document.getElementById('uncontrolled'));
</code></pre>

Thank you.

**Comment by chenglou** [comment]
#30 raised this too. This is fixed now; thanks!
