### ISSUE TITLE
0.4.4 broken?

### ISSUE THREAD

**Issue by walac** [chenglou/react-treeview#33]
After upgrading to 0.4.4, `require("react-treeview")` cannot find the package anymore. Looking inside `node_modules/react-treeview`, it feels like some files are missing.

**Comment by jeremiahrhall** [comment]
The `lib/react-treeview.js` file is missing. @chenglou 0.4.4 is completely unusable right now.

**Comment by chenglou** [comment]
Thanks for the ping, otherwise I'd have missed it, ugh. How is it now?

**Comment by jeremiahrhall** [comment]
0.4.5 works great. Thanks!
