### ISSUE TITLE
Unknown Prop 'defaultCollapsed' on <div> tag

### ISSUE THREAD

**Issue by ianhowe76** [chenglou/react-treeview#35]
I am using the defaultCollapsed prop to set the initial state of the tree
With react 15.2.1 I get the following console warning

"Warning: Unknown prop `defaultCollapsed` on <div> tag. Remove this prop from the element."

This is due to the ...rest props passed into the arrow component

**Comment by szalansun** [comment]
Same problem here.

**Comment by lerayj** [comment]
Same for me.

**Comment by oleg-rdk** [comment]
also have this

**Comment by chenglou** [comment]
Sorry for the delay! Merged and published as 0.4.6.

Please ping me (this way I get a notice) if anything goes wrong!
