### ISSUE TITLE
Enter "npm install react-treeview" command error

### ISSUE THREAD

**Issue by annzhou123** [chenglou/react-treeview#39]
Enter "npm install react-treeview" command and it has a error, how should I deal with ? The error was .
UNKNOWN-10-82-53-X:react-treeview-master labuser$ npm install react-treeview
npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/Cellar/node/5.7.0/bin/node" "/usr/local/bin/npm" "install" "react-treeview"
npm ERR! node v5.7.0
npm ERR! npm  v4.1.1
npm ERR! code ENOSELF

npm ERR! Refusing to install package with name "react-treeview" under a package
npm ERR! also called "react-treeview". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR! 
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/labuser/Downloads/react-treeview-master/npm-debug.log

Thanks!

**Comment by chenglou** [comment]
You've named your own package react-treeview =P. Changing the name fixes it.

Closing!
