### ISSUE TITLE
PropTypes via the main React package is deprecated

### ISSUE THREAD

**Issue by lynnchin** [chenglou/react-treeview#44]
warning.js:36 Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

Warning: TreeView: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

New release version of React (15.5.0) add new Warning that React.PropTypes will be deprecated soon. You must use the prop-types package from npm, and also React.createClass is deprecated as well.

**Comment by chenglou** [comment]
Thanks, fixed!
