### ISSUE TITLE
your demos can't be accessed anymore?

### ISSUE THREAD

**Issue by xyzdata** [chenglou/react-treeview#60]
your demos can't be accessed anymore?

**Comment by xyzdata** [comment]
![image](https://user-images.githubusercontent.com/29531779/38179826-1a3a76ec-365a-11e8-8f7b-0fa01fbf4428.png)


> Maybe you should publish it on Github pages.

**Comment by chenglou** [comment]
Still works from here; it's possible that it's blocked in China? In which case, you'll need to clone the repo and build the demos yourself.

Closing for now

**Comment by xyzdata** [comment]
# Yeah, I'm in the guard of `GWF`.

> freedom === `VPN` + google 

![image](https://user-images.githubusercontent.com/29531779/40829619-93ac0730-65b6-11e8-845d-50f7565e7daa.png)
